const ACTION_TYPES={
    REST_LOADİNG:"REST_LOADİNG",
    REST_ERROR:"REST_ERROR",
    REST_SUCCESS:"REST_SUCCESS",

     BASKET_LOADİNG:"BASKET_LOADİNG",
    BASKET_ERROR:"BASKET_ERROR",
    BASKET_SUCCESS:"BASKET_SUCCESS",
    ADD_TO_SUCCESS:"ADD_TO_SUCCESS",
    UPDATE_ITEM:"UPDATE_ITEM",
    REMOVE_ITEM:"REMOVE_FROM_BASKET",
    
}

export default ACTION_TYPES;